  vi: {
    nav: {
      home: 'Trang chủ',
      becomeFranchisor: 'Tôi muốn tuyển đại lý',
      becomeFranchisee: 'Tôi muốn nhận nhượng quyền',
      overseasAcademy: 'Học viện',
      overseasNews: 'Tin tức',
      overseasCase: 'Case study',
      overseasTips: 'Kiến thức',
      overseasPolicy: 'Chính sách',
      overseasDynamic: 'Xu hướng',
      overseasQA: 'Hỏi đáp',
      overseasServices: 'Dịch vụ xuất khẩu',
      aboutUs: 'Về chúng tôi',
      search: 'Tìm kiếm thương hiệu...',
      admin: 'Quản trị',
    },
    home: {
      title: 'Tìm',
      highlight: 'Nhượng quyền phù hợp',
      subtitle: 'Khám phá cơ hội nhượng quyền trong ngành F&B, trà, cà phê, đồ ăn vặt, tráng miệng. Phí nhượng quyền thật, điều kiện chi tiết và hướng dẫn đầy đủ',
      searchPlaceholder: 'Nhập tên thương hiệu, ngành hoặc từ khóa...',
      searchButton: 'Tìm kiếm',
      quickFilter: 'Lọc nhanh:',
      stats: {
        brands: 'Thương hiệu',
        industries: 'Ngành',
        daily: 'Cập nhật hàng ngày',
      },
      categories: 'Danh mục phổ biến',
      viewAll: 'Xem tất cả →',
      newBrands: 'Dự án Nhượng quyền Hot',
      latest: 'Mới nhất',
      feeLowToHigh: 'Phí: Thấp→Cao',
      feeHighToLow: 'Phí: Cao→Thấp',
      whyChooseUs: 'Tại sao chọn China Franchise Net',
      features: {
        reliable: { title: 'Đáng tin cậy', desc: 'Tất cả thông tin thương hiệu được kiểm duyệt thủ công để đảm bảo chính xác' },
        dailyUpdate: { title: 'Cập nhật hàng ngày', desc: 'Thu thập 10 thương hiệu mới mỗi ngày, mở rộng thư viện thương hiệu liên tục' },
        transparent: { title: 'Minh bạch', desc: 'Công khai phí nhượng quyền, tổng chi phí và thờigian hoàn vốn' },
        mobile: { title: 'Tương thích di động', desc: 'Tối ưu hóa cho điện thoại và máy tính bảng' },
      },
    },
    brandCard: {
      franchiseFee: 'Phí nhượng quyền',
      totalCost: 'Tổng chi phí',
      stores: 'Cửa hàng',
    },
    brand: {
      franchiseFee: 'Phí nhượng quyền',
      totalCost: 'Tổng chi phí',
      stores: 'Số cửa hàng',
      contractYears: 'Hợp đồng',
      inquiry: 'Tư vấn ngay',
      backToList: 'Quay lại danh sách',
      process: 'Quy trình nhượng quyền',
      support: 'Hỗ trợ',
      gallery: 'Thư viện ảnh',
      basicInfo: 'Thông tin cơ bản',
      industry: 'Ngành',
      source: 'Nguồn',
      storeCount: 'Số cửa hàng',
      viewCount: 'Lượt xem',
      relatedBrands: 'Thương hiệu liên quan',
    },
    inquiry: {
      title: 'Tư vấn ngay',
      subtitle: 'Tư vấn viên sẽ liên hệ bạn trong vòng 24 giờ',
      name: 'Họ tên *',
      phone: 'Số điện thoại *',
      email: 'Email (Tùy chọn)',
      message: 'Tin nhắn (Tùy chọn)',
      submit: 'Gửi yêu cầu',
      submitting: 'Đang gửi...',
      success: 'Gửi thành công!',
      successDesc: 'Tư vấn viên sẽ liên hệ bạn trong vòng 24 giờ. Vui lòng giữ máy.',
      privacy: 'Thông tin của bạn chỉ dùng để liên hệ, không chia sẻ cho bên thứ ba.',
    },
    contactModal: {
      title: 'Chọn phương thức liên hệ',
      wechat: 'WeChat',
      whatsapp: 'WhatsApp',
      phone: 'Điện thoại',
      email: 'Email',
      wechatId: 'WeChat ID',
      copy: 'Sao chép',
      copied: 'Đã sao chép',
    },
    footer: {
      slogan: 'Khám phá các thương hiệu nhượng quyền chất lượng trong ngành F&B, trà, cà phê, đồ ăn vặt, tráng miệng.',
      quickLinks: 'Liên kết nhanh',
      contactUs: 'Liên hệ',
      onlineInquiry: 'Hỏi đáp',
      admin: 'Quản trị',
      hotIndustries: 'Ngành phổ biến',
      categoryBrands: 'Thương hiệu quốc tế',
      budget: 'Ngân sách',
      aboutUs: 'Về chúng tôi',
      copyright: '© 2026 China Franchise Net. Bảo lưu mọi quyền.',
      tagline: 'Thương hiệu nhượng quyền chất lượng cho doanh nhân thành công',
    },
    common: {
      loading: 'Đang tải...',
      noData: 'Không có dữ liệu',
      viewDetails: 'Xem chi tiết',
    },
  },
};

export function getTranslation(locale: Locale) {
  return translations[locale as keyof typeof translations] ?? translations.zh;
}
